webserverSecretKey: <Put your key there>

dags:
  gitSync:
    enabled: true
    repo: https://github.com/fabricemlili/weather-tracker.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"
